
#ifndef Q242_UNITTEST_H__
#define Q242_UNITTEST_H__
#include <gtest/gtest.h>

#include "../src/q0242.hpp"
using namespace std;

/**
  * this file is generated by gquestion.py
  *
  * 242. Valid Anagram
  *
  * Given two strings s and t , return true if t is
  * an anagram of s , and false otherwise .
  *
  * Constraints:
  * -  1 <= s.length, t.length <= 5 * 10^(4) 
  * -  s and t consist of lowercase English letters.
  *  “Follow up:“ What if the inputs contain Unicode characters? How would you adapt your solution to such a case?
  *
*/

TEST(q242, sample_input01) {
  string s = "anagram";
  string t = "nagaram";
  bool exp = true;
  l242::Solution solver;
  EXPECT_EQ(solver.isAnagram(s, t), exp);
}

TEST(q242, sample_input02) {
  string s = "rat";
  string t = "car";
  bool exp = false;
  l242::Solution solver;
  EXPECT_EQ(solver.isAnagram(s, t), exp);
}

#endif