
#ifndef LEETCODE_Q461_H__
#define LEETCODE_Q461_H__
#include <iostream>

namespace l461 {
using namespace std;

/**
 * This file is generated by leetcode_add.py
 *
 * 461.
 *      Hamming Distance
 *
 * ––––––––––––––––––––––––––––– Description –––––––––––––––––––––––––––––
 *
 *   The <a href="https://en.wikipedia.org/wiki/Hamming_distance"
 *   target="_blank">Hamming distance</a> between two integers is the
 *   number of positions at which the corresponding bits are
 *   Given two integers ‘x’ and ‘y’ , return “the “Hamming distance”
 *   between them” .
 *
 * ––––––––––––––––––––––––––––– Constraints –––––––––––––––––––––––––––––
 *
 *   • ‘0 ≤x, y ≤ 2³¹ - 1’
 *
 */

class Solution {
 public:
  int hammingDistance(int x, int y) {
    return __builtin_popcount(x ^ y);
  }
};
}  // namespace l461

#endif