
#ifndef LEETCODE_Q9_H__
#define LEETCODE_Q9_H__
#include <iostream>

namespace l9 {
using namespace std;

/**
  * This file is generated by leetcode_add.py
  *
  * 9.
  *    Palindrome Number
  *
  * ––––––––––––––––––––––––––––– Description –––––––––––––––––––––––––––––
  *
  *   Given an integer ‘x’ , return ‘true’ if ‘x’ is palindrome integer.
  *   
  *   An integer is a “palindrome” when it reads the same backward as
  *   forward. For example, ‘121’ is palindrome while ‘123’ is not.
  *
  * ––––––––––––––––––––––––––––– Constraints –––––––––––––––––––––––––––––
  *
  *   • ‘-2³¹≤ x ≤ 2³¹- 1’
  *
*/

class Solution {
 public:
  bool isPalindrome(int x) {
    if (x < 0) return false;
    double tmp = x;
    double reverse = 0;

    while (x > 0) {
      reverse = reverse * 10 + x % 10;
      x /= 10;
    }

    return reverse == tmp;
  }
};
}  // namespace l9

#endif