
#ifndef LEETCODE_Q14_H__
#define LEETCODE_Q14_H__
#include <iostream>
#include <string>
#include <vector>

namespace l14 {
using namespace std;

/**
 * This file is generated by leetcode_add.py
 *
 * 14.
 *     Longest Common Prefix
 *
 * ––––––––––––––––––––––––––––– Description –––––––––––––––––––––––––––––
 *
 *   Write a function to find the longest common prefix string amongst an
 *   array of
 *   If there is no common prefix, return an empty string ‘''’ .
 *
 * ––––––––––––––––––––––––––––– Constraints –––––––––––––––––––––––––––––
 *
 *   • ‘1 ≤ strs.length ≤ 200’
 *   • ‘0 ≤ strs[i].length ≤ 200’
 *   • ‘strs[i]’ consists of only lower-case English letters.
 *
 */

class Solution {
 public:
  string longestCommonPrefix(vector<string>& strs) {
    string res = "";
    for (int i = 0; i < strs.front().size(); ++i) {
      char c = strs.front()[i];
      bool common = true;
      for (int j = 1; j < strs.size() && common; ++j)
        common &= strs[j][i] == c;
        
      if (common) res.push_back(c);
      else break;
    }
    return res;
  }
};
}  // namespace l14

#endif