
#ifndef Q26_UNITTEST_H__
#define Q26_UNITTEST_H__
#include <gtest/gtest.h>

#include "q0026.hpp"
using namespace std;

/**
 * This file is generated by leetcode_add.py
 *
 * 26.
 *     Remove Duplicates from Sorted Array
 *
 * ––––––––––––––––––––––––––––– Description –––––––––––––––––––––––––––––
 *
 *   Given an integer array ‘nums’ sorted in “non-decreasing order” ,
 *   remove the duplicates <a
 *   href="https://en.wikipedia.org/wiki/In-place_algorithm"
 *   target="_blank"> “in-place” </a> such that each unique element appears
 *   only “once” . The “relative order” of the elements should be kept the
 *   “same”
 *   Since it is impossible to change the length of the array in some
 *   languages, you must instead have the result be placed in the “first
 *   part” of the array ‘nums’ . More formally, if there are ‘k’ elements
 *   after removing the duplicates, then the first ‘k’ elements of ‘nums’
 *   should hold the final result. It does not matter what you leave beyond
 *   the first ‘k’
 *   Return ‘k’ “ after placing the final result in the first ” ‘k’ “ slots
 *   of ” ‘nums’
 *   Do “not” allocate extra space for another array. You must do this by
 *   “modifying the input array <a
 *   href="https://en.wikipedia.org/wiki/In-place_algorithm"
 *   target="_blank">in-place</a>” with O(1) extra
 *    “Custom Judge:”
 *   The judge will test your solution with the following
 *   int[] nums = [...]; // Input
 *   int[] expectedNums = [...]; // The expected answer with correct
 *   int k = removeDuplicates(nums); // Calls your
 *   assert k ==
 *   for (int i = 0; i < k; i++)
 *       assert nums[i] ==
 *   If all assertions pass, then your solution will be “accepted” .
 *
 * ––––––––––––––––––––––––––––– Constraints –––––––––––––––––––––––––––––
 *
 *   • ‘0 ≤ nums.length ≤ 3 × 10⁴’
 *   • ‘-100 ≤ nums[i] ≤ 100’
 *   • ‘nums’ is sorted in “non-decreasing” order.
 *
 */

TEST(q26, sample_input01) {
  l26::Solution solver;
  vector<int> nums = {1, 1, 2};
  int exp = 2;
  EXPECT_EQ(solver.removeDuplicates(nums), exp);
}

TEST(q26, sample_input02) {
  l26::Solution solver;
  vector<int> nums = {0, 0, 1, 1, 1, 2, 2, 3, 3, 4};
  int exp = 5;
  EXPECT_EQ(solver.removeDuplicates(nums), exp);
}

#endif