
#ifndef Q567_UNITTEST_H__
#define Q567_UNITTEST_H__
#include <gtest/gtest.h>

#include "q0567.hpp"
using namespace std;

/**
  * this file is generated by gquestion.py
  *
  * 567. Permutation in String
  *
  * Given two strings s1 and s2 , return true if s2
  * contains a permutation of s1 , or false otherwise .
  * In other words, return true if one of s1 ';s
  * permutations is the substring of s2 .
  *
  * Constraints:
  * -  1 <= s1.length, s2.length <= 10^(4) 
  * -  s1 and s2 consist of lowercase English letters.
  *
*/

TEST(q567, sample_input01) {
  string s1 = "ab";
  string s2 = "eidbaooo";
  bool exp = true;
  l567::Solution solver;
  EXPECT_EQ(solver.checkInclusion(s1, s2), exp);
}

TEST(q567, sample_input02) {
  string s1 = "ab";
  string s2 = "eidboaoo";
  bool exp = false;
  l567::Solution solver;
  EXPECT_EQ(solver.checkInclusion(s1, s2), exp);
}

TEST(q567, input01) {
  string s1 = "adc";
  string s2 = "dcda";
  bool exp = true;
  l567::Solution solver;
  EXPECT_EQ(solver.checkInclusion(s1, s2), exp);
}

TEST(q567, input02) {
  string s1 = "horse";
  string s2 = "ros";
  bool exp = false;
  l567::Solution solver;
  EXPECT_EQ(solver.checkInclusion(s1, s2), exp);
}

#endif