#include <gtest/gtest.h>
#include <iostream>

using namespace std;

/**
 * This file is generated by leetcode_add.py
 *
 * 1716.
 *       Calculate Money in Leetcode Bank
 *
 * ––––––––––––––––––––––––––––– Description –––––––––––––––––––––––––––––
 *
 *   Hercy wants to save money for his first car. He puts money in the
 *   Leetcodebank “every day”
 *   He starts by putting in ‘$1’ on Monday, the first day. Every day from
 *   Tuesday to Sunday, he will put in ‘$1’ more than the day before. On
 *   every subsequent Monday, he will put in ‘$1’ more than the “previous
 *   Monday” .<span style="display: none;">
 *   Given ‘n’ , return “the total amount of money he will have in the
 *   Leetcode bank at the end of the ” ‘nᵗʰ’ “ day.”
 *
 * ––––––––––––––––––––––––––––– Constraints –––––––––––––––––––––––––––––
 *
 *   • ‘1 ≤ n ≤ 1000’
 *
 */

struct q1716 : public ::testing::Test {
  // Leetcode answer here
  class Solution {
  public:
    int totalMoney(int n) {
      auto m    = (n - 1) / 7;
      auto k    = (n - 1) % 7 + 1;
      int  sum1 = (28 + 28 + (m - 1) * 7) * m / 2;
      int  sum2 = (m + 1 + m + k) * k / 2;
      return sum1 + sum2;
    }
  };

  class Solution *solution;
};

TEST_F(q1716, NOT_IMPLEMENT) { EXPECT_TRUE("NOT IMPLEMENT"); }
