
#ifndef Q59_UNITTEST_H__
#define Q59_UNITTEST_H__
#include <gtest/gtest.h>

#include "q0059.hpp"
using namespace std;

/**
  * this file is generated by gquestion.py
  *
  * 59. Spiral Matrix II
  *
  * Given a positive integer n , generate an n x n
  * matrix filled with elements from 1 to n^(2) in
  * spiral order.
  *
  * Constraints:
  * -  1 <= n <= 20 
  *
*/

TEST(q59, sample_input01) {
  int n = 3;
  vector<vector<int>> exp = {{1, 2, 3}, {8, 9, 4}, {7, 6, 5}};
  l59::Solution solver;
  EXPECT_EQ(solver.generateMatrix(n), exp);
}

TEST(q59, sample_input02) {
  int n = 1;
  vector<vector<int>> exp = {{1}};
  l59::Solution solver;
  EXPECT_EQ(solver.generateMatrix(n), exp);
}

#endif