
#ifndef LEETCODE_Q70_H__
#define LEETCODE_Q70_H__
#include <iostream>

namespace l70 {
using namespace std;

/**
  * this file is generated by gquestion.py
  *
  * 70. Climbing Stairs
  *
  * You are climbing a staircase. It takes n steps to
  * reach the top.
  * Each time you can either climb 1 or 2 steps. In
  * how many distinct ways can you climb to the top?
  *
  * Constraints:
  * -  1 <= n <= 45 
  *
*/
class Solution {
 public:
  int climbStairs(int n) {
    int ret = 0;
    for (int i = 0; 2 * i <= n; i++) {
      double count = 1;
      int num_step = n - i;
      for (int j = 0; j < i; j++) {
        count *= (double)(num_step - j) / (double)(j + 1);
      }
      ret += (int)(count + 0.5);
    }
    return ret;
  }
};
}  // namespace l70
#endif