
#ifndef LEETCODE_Q94_H__
#define LEETCODE_Q94_H__
#include <iostream>
#include <leetcode/tree_node.hpp>
#include <vector>

namespace l94 {
using namespace std;

/**
  * this file is generated by gquestion.py
  *
  * 94. Binary Tree Inorder Traversal
  *
  * Given the root of a binary tree, return the
  * inorder traversal of its nodes'; values .
  *
  * Constraints:
  * - The number of nodes in the tree is in the range [0, 100] .
  * -  -100 <= Node.val <= 100 
  *  “Follow up:“ Recursive solution is trivial, could you do it iteratively?
  *
*/
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
 private:
  void helper(TreeNode *p, vector<int> &re) {
    if (p == nullptr) return;
    helper(p->left, re);
    re.push_back(p->val);
    helper(p->right, re);
  }

 public:
  vector<int> inorderTraversal(TreeNode *root) {
    vector<int> res;
    helper(root, res);
    return res;
  }
};
}  // namespace l94
#endif