
#ifndef LEETCODE_Q242_H__
#define LEETCODE_Q242_H__
#include <iostream>
#include <string>
#include <unordered_map>

namespace l242 {
using namespace std;

/**
  * this file is generated by gquestion.py
  *
  * 242. Valid Anagram
  *
  * Given two strings s and t , return true if t is
  * an anagram of s , and false otherwise .
  *
  * Constraints:
  * -  1 <= s.length, t.length <= 5 * 10^(4) 
  * -  s and t consist of lowercase English letters.
  *  “Follow up:“ What if the inputs contain Unicode characters? How would you adapt your solution to such a case?
  *
*/
class Solution {
 public:
  bool isAnagram(string s, string t) {
    if (s.size() != t.size()) return false;
    unordered_map<char, int> hash;
    for (const auto &c : s) ++hash[c];
    for (const auto &c : t)
      if (!hash.count(c) || --hash[c] < 0)
        return false;
    return true;
  }
};
}  // namespace l242
#endif