// Copyright 2023 Naon Lu
//
// This file describes the solution of
// Find the Difference
//
// https://leetcode.com/problems/find-the-difference/
//
// Question ID: 389
// Difficult  : Easy
// Solve Date : 2022/02/07 18:13

#include <iosfwd>
#include <string>

// -- This header must be included after others --
#include "leetcode/testing/solution_test_helper.h"

using namespace std;
using namespace lcd;

// Description of |389. Find the Difference|:
//
// You are given two strings |s| and |t|.
// String |t| is generated by random shuffling string |s| and then add one more
// letter at a random position. Return the letter that was added to |t|.  
//

LEETCODE_BEGIN_RESOLVING(389, FindTheDifference, Solution);

class Solution {
public:
  char findTheDifference(string s, string t) {
    vector<int> cnt(26, 0);
    for (const auto &c : s)
      ++cnt[c - 'a'];
    for (const auto &c : t)
      --cnt[c - 'a'];
    for (int i = 0; i < cnt.size(); ++i) {
      if (cnt[i] != 0)
        return 'a' + i;
    }
    return ' ';
  }
};

LEETCODE_END_RESOLVING(Solution);

///////////////////////////////////////////////////////////////////////////////
// The following is test data for unit test.
// Note that inputs should be obey the constraints mentioned in LeetCode:
// * |0 <= s.length <= 1000|
// * |t.length == s.length + 1|
// * |s| and |t| consist of lowercase English letters.
///////////////////////////////////////////////////////////////////////////////

// [Example #1]
//  Input: s = "abcd", t = "abcde"
// Output: "e"
//
// 'e' is the letter that was added.

LEETCODE_SOLUTION_UNITTEST(389, FindTheDifference, example_1) {
  auto   solution = MakeSolution();
  string s        = "abcd";
  string t        = "abcde";
  char   expect   = 'e';
  char   actual   = solution->findTheDifference(s, t);
  LCD_EXPECT_EQ(expect, actual);
}

// [Example #2]
//  Input: s = "", t = "y"
// Output: "y"
//

LEETCODE_SOLUTION_UNITTEST(389, FindTheDifference, example_2) {
  auto   solution = MakeSolution();
  string s        = "";
  string t        = "y";
  char   expect   = 'y';
  char   actual   = solution->findTheDifference(s, t);
  LCD_EXPECT_EQ(expect, actual);
}
