
#ifndef LEETCODE_Q415_H__
#define LEETCODE_Q415_H__
#include <iostream>
#include <string>
#include <vector>

namespace l415 {
using namespace std;

/**
  * this file is generated by gquestion.py
  *
  * 415. Add Strings
  * Given two non-negative integers, num1 and num2
  * represented as string, return the sum of num1 and
  * num2 as a string .
  * You must solve the problem without using any
  * built-in library for handling large integers (such as
  * BigInteger ). You must also not convert the inputs
  * to integers directly.
  *
  * Constraints:
  * -  1 <= num1.length, num2.length <= 10^(4) 
  * -  num1 and num2 consist of only digits.
  * -  num1 and num2 don';t have any leading zeros except for the zero itself.
  *
*/
class Solution {
 public:
  string addStrings(string num1, string num2) {
    string res;
    res.reserve(max(num1.size(), num2.size()) + 1);
    int i = num1.size() - 1, j = num2.size() - 1;
    int carry = 0;

    while (i >= 0 || j >= 0 || carry) {
      int cur = (i >= 0 ? num1[i] - '0' : 0) +
                (j >= 0 ? num2[j] - '0' : 0) + carry;
      carry = cur / 10;
      cur %= 10;

      res.push_back(cur + '0');
      i--, j--;
    }

    reverse(res.begin(), res.end());

    return res;
  }
};
}  // namespace l415
#endif