
#ifndef LEETCODE_Q263_H__
#define LEETCODE_Q263_H__
#include <iostream>

namespace l263 {
using namespace std;

/**
 * This file is generated by leetcode_add.py
 *
 * 263.
 *      Ugly Number
 *
 * ––––––––––––––––––––––––––––– Description –––––––––––––––––––––––––––––
 *
 *   An “ugly number” is a positive integer whose prime factors are limited
 *   to ‘2’ , ‘3’ , and ‘5’
 *   Given an integer ‘n’ , return ‘true’ “if” ‘n’ “is an “ugly number” ” .
 *
 * ––––––––––––––––––––––––––––– Constraints –––––––––––––––––––––––––––––
 *
 *   • ‘-2³¹ ≤ n ≤ 2³¹ - 1’
 *
 */

class Solution {
 public:
  bool isUgly(int n) {
    if (n == 0) return false;
    if (n == 1) return true;
    while (n % 2 == 0)
      n /= 2;
    while (n % 3 == 0)
      n /= 3;
    while (n % 5 == 0)
      n /= 5;
    return n == 1;
  }
};
}  // namespace l263

#endif